# Numpy
- general purpose array-processing package
- provides high-performance multidimensional array object and tools for working with these arrays

# Arrays
- data structure that stores value of same data type.

In [125]:
import numpy as np

In [126]:
lst = [1,2,3,4,5]

arr = np.array(lst) #creating 1D array of lst


In [127]:
type(arr)

numpy.ndarray

In [128]:
# Multidimensional array
lst1 = [1,2,3,4,5]
lst2 = [1,3,5,7,9]
lst3 = [2,4,6,8,10]

arr1 = np.array([lst1,lst2,lst3])

In [129]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [130]:
# checking shape
arr1.shape

(3, 5)

In [131]:
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  1],
       [ 3,  5,  7],
       [ 9,  2,  4],
       [ 6,  8, 10]])

While reshaping the array,<br> no of element before = no of element after reshaping<br> 
In below code, before = 2x6 = 12<br> after = 4x3 = 12

In [132]:
l = [1,2,3,4,5,6]
a = [2,3,5,7,3,9]
arr2 = np.array([l,a])
arr2

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 5, 7, 3, 9]])

In [133]:
arr2.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 5],
       [7, 3, 9]])

### Indexing

In [134]:
# accessing array element
arr 

array([1, 2, 3, 4, 5])

In [135]:
arr[3]

4

In [136]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [137]:
arr1[1:,:2]

array([[1, 3],
       [2, 4]])

In [138]:
arr1[:,:2]

array([[1, 2],
       [1, 3],
       [2, 4]])

In [139]:
arr1[1:,2:4]

array([[5, 7],
       [6, 8]])

In [140]:
# copy() function and broadcasting
arr1[2:] = 100
arr1

array([[  1,   2,   3,   4,   5],
       [  1,   3,   5,   7,   9],
       [100, 100, 100, 100, 100]])

In [141]:
arr1[2:]=100
arr1

array([[  1,   2,   3,   4,   5],
       [  1,   3,   5,   7,   9],
       [100, 100, 100, 100, 100]])

In [142]:
arr2 = arr1

In [143]:
arr2[3:]=500
arr2

array([[  1,   2,   3,   4,   5],
       [  1,   3,   5,   7,   9],
       [100, 100, 100, 100, 100]])

In [144]:
arr2 = arr1.copy()

In [145]:
print(arr1)
arr2[2:]=300
print(arr2)

[[  1   2   3   4   5]
 [  1   3   5   7   9]
 [100 100 100 100 100]]
[[  1   2   3   4   5]
 [  1   3   5   7   9]
 [300 300 300 300 300]]


In [146]:
# arranging array
arr3 = np.arange(0,10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
arr3 = np.arange(0,10,step=3)
arr3

array([0, 3, 6, 9])

In [148]:
np.linspace(1,2,4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [149]:
# condition for Explatory data analysis
val = 2
arr*2

array([ 2,  4,  6,  8, 10])

In [156]:
a=np.arange(0,12).reshape(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [157]:
b=np.arange(2,14).reshape(2,6)
b

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13]])

In [158]:
a*b

array([[  0,   3,   8,  15,  24,  35],
       [ 48,  63,  80,  99, 120, 143]])

In [165]:
np.ones((4,2),dtype=int) # all array element 1

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [166]:
#random distribution
np.random.rand(2,2)

array([[0.69098275, 0.78819261],
       [0.58528946, 0.58437628]])

In [169]:
# randn=random value based on standart normal distribution
np.random.randn(2,2)

array([[ 0.59512546, -1.40013413],
       [-0.69910601,  0.8610149 ]])

In [172]:
#randint = select 4 random value between 0 and 50
np.random.randint(0,50,4).reshape(2,2)

array([[38, 30],
       [ 1, 32]])